services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    container_name: backend
    env_file:
      - .env.build
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
