services:

  backend:
    image: globalexplorer-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env
    restart: always
    ports:
      - "3000:3000"

  frontend:
    image: globalexplorer-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    restart: always
    ports:
      - "80:80"