version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - myredis
    networks:
      - globalexplorer-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_BASE_URL: ${VITE_BASE_URL}
        VITE_MAP_API: ${VITE_MAP_API}
        VITE_IMG_URL: ${VITE_IMG_URL}
        VITE_RAZORPAY_KEY_ID: ${VITE_RAZORPAY_KEY_ID}
        VITE_GET_GEOLOCATION: ${VITE_GET_GEOLOCATION}
    container_name: frontend
    env_file:
      - ./frontend/.env
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - globalexplorer-network

  myredis:
    image: redis:7
    container_name: myredis
    ports:
      - "6379:6379"
    networks:
      - globalexplorer-network

networks:
  globalexplorer-network:
    driver: bridge
