# docker-compose.deploy.yml
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always

  backend:
    image: globalexplorer-backend:latest  # <-- Specifies the image to pull
    # NO 'build:' SECTION
    container_name: backend
    # 'env_file' is removed as Azure will not read it.
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: always
    ports:
      - "3000:3000"

  frontend:
    image: globalexplorer-frontend:latest # <-- Specifies the image to pull
    # NO 'build:' SECTION
    container_name: frontend
    depends_on:
      - backend
    restart: always
    ports:
      - "80:80"