services:

  backend:
    image: ACR_LOGIN_SERVER/globalexplorer-backend:latest
    container_name: backend
    restart: always
    ports:
      - "3000:3000"

  frontend:
    image: ACR_LOGIN_SERVER/globalexplorer-frontend:latest
    container_name: frontend
    depends_on:
      - backend
    restart: always
    ports:
      - "80:80"