# docker-compose.deploy.yml
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always

  backend:
    image: ACR_LOGIN_SERVER/globalexplorer-backend:latest  # <-- CHANGED
    container_name: backend
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: always
    ports:
      - "3000:3000"

  frontend:
    image: ACR_LOGIN_SERVER/globalexplorer-frontend:latest # <-- CHANGED
    container_name: frontend
    depends_on:
      - backend
    restart: always
    ports:
      - "80:80"